In [13]:
import jax.numpy as jnp
from jax import jit, vmap, grad

In [2]:
def f(x,y):
    return jnp.dot(x,y)

In [19]:
x=jnp.linspace(0,1,11)
y=jnp.linspace(1,2,11)

In [21]:
f(x,y)

DeviceArray(9.35, dtype=float32)

In [22]:
grad(f,argnums=0)(x,y)

DeviceArray([1.       , 1.1      , 1.2      , 1.3      , 1.4000001,
             1.5      , 1.6      , 1.7      , 1.8      , 1.9000001,
             2.       ], dtype=float32)

In [24]:
X=jnp.linspace(0,1,55).reshape(5,11)

In [26]:
vmap(grad(f,argnums=0),(0,None),0)(X,y)

DeviceArray([[1.       , 1.1      , 1.2      , 1.3      , 1.4000001,
              1.5      , 1.6      , 1.7      , 1.8      , 1.9000001,
              2.       ],
             [1.       , 1.1      , 1.2      , 1.3      , 1.4000001,
              1.5      , 1.6      , 1.7      , 1.8      , 1.9000001,
              2.       ],
             [1.       , 1.1      , 1.2      , 1.3      , 1.4000001,
              1.5      , 1.6      , 1.7      , 1.8      , 1.9000001,
              2.       ],
             [1.       , 1.1      , 1.2      , 1.3      , 1.4000001,
              1.5      , 1.6      , 1.7      , 1.8      , 1.9000001,
              2.       ],
             [1.       , 1.1      , 1.2      , 1.3      , 1.4000001,
              1.5      , 1.6      , 1.7      , 1.8      , 1.9000001,
              2.       ]], dtype=float32)

In [27]:
X=jnp.linspace(0,1,55).reshape(5,11)
Y=jnp.linspace(1,2,55).reshape(5,11)

In [28]:
vmap(grad(f,argnums=0),(0,0),0)(X,Y)

DeviceArray([[1.       , 1.0185186, 1.037037 , 1.0555556, 1.074074 ,
              1.0925926, 1.1111112, 1.1296296, 1.1481481, 1.1666666,
              1.1851852],
             [1.2037036, 1.2222222, 1.2407408, 1.2592592, 1.2777778,
              1.2962964, 1.3148148, 1.3333333, 1.3518519, 1.3703704,
              1.3888888],
             [1.4074074, 1.425926 , 1.4444444, 1.4629629, 1.4814816,
              1.5      , 1.5185184, 1.537037 , 1.5555556, 1.574074 ,
              1.5925926],
             [1.6111112, 1.6296296, 1.6481482, 1.6666667, 1.6851852,
              1.7037036, 1.7222222, 1.7407408, 1.7592592, 1.7777778,
              1.7962964],
             [1.8148148, 1.8333333, 1.8518519, 1.8703704, 1.8888888,
              1.9074074, 1.925926 , 1.9444444, 1.962963 , 1.9814816,
              2.       ]], dtype=float32)