In [2]:
from jax.lax import scan
from jax.lax import dynamic_slice
import jax.numpy as jnp

In [4]:


N = 30
M = 10
a = jnp.arange(N)

print(dynamic_slice(a, (10,), (M,)))


[10 11 12 13 14 15 16 17 18 19]


In [9]:
c = jnp.array([1,3,7])

def scan_slice():

    def f(icarry,factor):
        element = dynamic_slice(a, (icarry,), (M,))
        return icarry+M, element*factor
    
    _, result = scan(f, 0, c)

    return result


In [10]:
print(scan_slice())

[[  0   1   2   3   4   5   6   7   8   9]
 [ 30  33  36  39  42  45  48  51  54  57]
 [140 147 154 161 168 175 182 189 196 203]]
