In [2]:
import jax.numpy as jnp
import numpy as np
#from jax.ops import index_add,index_update
#from jax.ops import index as joi

In [12]:
N=5
a=jnp.zeros(N)

In [4]:
a

Array([0., 0., 0., 0., 0.], dtype=float32)

In [13]:
indx=jnp.array([1,2])
val=jnp.array([10.0,3.0])

In [6]:
#a[indx]=val

In [15]:
a=a.at[indx].set(val)

In [17]:
a

Array([ 0., 10.,  3.,  0.,  0.], dtype=float32)

In [16]:
a.at[jnp.array([0,1])].add(jnp.array([1.,2.]))

Array([ 1., 12.,  3.,  0.,  0.], dtype=float32)

## 2D case

In [16]:
N=4
M=3
a=jnp.zeros((N,M))

In [17]:
a

DeviceArray([[0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.]], dtype=float32)

In [18]:
indx=jnp.array([1,2])
indy=jnp.array([0,2])
val=jnp.array([10.0,3.0])

In [20]:
a=index_update(a,joi[indx,indy],val)

In [21]:
a

DeviceArray([[ 0.,  0.,  0.],
             [10.,  0.,  0.],
             [ 0.,  0.,  3.],
             [ 0.,  0.,  0.]], dtype=float32)